--DakTank
--E2Helper.Descriptions[""] = ""
E2Helper.Descriptions["daktankArmor"] = "Returns raw armor value of entity."
E2Helper.Descriptions["daktankHealth"] = "Returns current health value of entity."
E2Helper.Descriptions["daktankMaxHealth"] = "Returns max health value of entity."
E2Helper.Descriptions["daktankGetName"] = "Returns entity name in daktank."
E2Helper.Descriptions["daktankGetAmmoType"] = "Returns gun's current ammo type."
E2Helper.Descriptions["daktankGetCooldownPerc"] = "Returns percentage remaining of gun's cooldown."
E2Helper.Descriptions["daktankGetAmmoCount"] = "Returns ammo count of a gun's currently selected shell."
E2Helper.Descriptions["daktankGetShellPenetration"] = "Returns average penetration of gun's currently selected shell."
E2Helper.Descriptions["daktankGetShellVelocity"] = "Returns average velocity of gun's currently selected shell."
E2Helper.Descriptions["daktankGetShellMass"] = "Returns average mass of gun's currently selected shell."
E2Helper.Descriptions["daktankGetShellDamage"] = "Returns average damage of gun's currently selected shell."